<?
/*********************************************************************/
/*     Client  Name  :  Global Cybersoft                             */
/*     System  Name  :  GCS Web Site                                 */
/*     Project Name  :  GCS Web Site                                 */
/*     Program Name  :  MySQL_Config.inc                             */
/*     Create Date   :  2008/09/16                                   */
/*     Programmer    :  hoangpm(GCS)                                 */
/*     Entry Server  :                                               */
/*     Called By     :  ALL                                          */
/*     File Code     :  SJIS                                         */
/*     Execute Env   :  EUC                                          */
/*     Copyright     :  Global Cybersoft.                            */
/*-------------------------------------------------------------------*/
/*     Comment       :                                               */
/*-------------------------------------------------------------------*/
/*     Version V001  :  2008/09/25 (hoangpm) New Create              */
/*********************************************************************/

//-------------------------------------------------------------------//
// Include My SQL Library
//-------------------------------------------------------------------//
include_once( "P_MySQL/P_MySQL_Real_SELECT_Function.inc" );
include_once( "P_MySQL/P_MySQL_Real_SELECT_GetArrayIndex_Function.inc" );
include_once( "P_MySQL/P_MySQL_Real_SELECT_GetArray_Function.inc" );
include_once( "P_MySQL/P_MySQL_Real_Exec_Function.inc" );
include_once( "P_MySQL/P_MySQL_SELECT_Function.inc" );
include_once( "P_MySQL/P_MySQL_Exec_Function.inc" );
include_once( "P_MySQL/P_MySQL_ErrorHandler_Function.inc" );
include_once( "P_SQL/P_SQL_Quote_Function.inc" );
include_once( "P_SQL/P_SQL_Quote_Like_Function.inc" );
include_once( "P_SQL/P_SQL_Quote_Number_Function.inc" );
include_once( "P_SQL/P_SQL_Quote_NumberOnly_Function.inc" );

?>
