<?php
/**************************************************************************************************/
/* Created on Nov 29, 2008                                                                        */
/**************************************************************************************************/
require_once( LIB_PATH . "P_MySQL/P_MySQL_Real_SELECT_Function.inc" );
require_once( LIB_PATH . "P_MySQL/P_MySQL_Real_SELECT_GetArrayIndex_Function.inc" );
require_once( LIB_PATH . "P_MySQL/P_MySQL_Real_SELECT_GetArray_Function.inc" );
require_once( LIB_PATH . "P_MySQL/P_MySQL_Real_Exec_Function.inc" );
require_once( LIB_PATH . "P_MySQL/P_MySQL_SELECT_Function.inc" );
require_once( LIB_PATH . "P_MySQL/P_MySQL_Exec_Function.inc" );
require_once( LIB_PATH . "P_MySQL/P_MySQL_ErrorHandler_Function.inc" );
require_once( LIB_PATH . "P_SQL/P_SQL_Quote_Function.inc" );
require_once( LIB_PATH . "P_SQL/P_SQL_Quote_Like_Function.inc" );
require_once( LIB_PATH . "P_SQL/P_SQL_Quote_Number_Function.inc" );
require_once( LIB_PATH . "P_SQL/P_SQL_Quote_NumberOnly_Function.inc" );
?>
